version: "2"
services: 
  bpg-csp-air-personalization-api-jmeter: 
    environment: 
      - ENV=$environment
      - "ARGS=-n -j /opt/scripts/$outdir/jmeter.log -t /opt/scripts/$jmxfile -l /opt/scripts/$outdir/$resultfile -Jhost=$host -Joutput_dir=$outdir -Jusers=$threads -Jduration=$duration -Jramp_up=$rampup"
      - "DASHBOARD_ARGS=-g /opt/scripts/$outdir/$resultfile -o /opt/scripts/dashboard"
      - OUTDIR=$outdir
      - BUCKETNAME=$bucketname
      - FILENAME=$resultfile
    image: "379831576876.dkr.ecr.us-west-2.amazonaws.com/bpg-csp/air-personalization-api-jmeter:$tag_version"
    cpu_shares: 1024
    mem_reservation: 1500m
    mem_limit: 8000m
    logging: 
      driver: awslogs
      options: 
        awslogs-group: /aws/ec2/$environment-air-personalization-api-perf-jmeter
        awslogs-region: us-west-2
        awslogs-stream-prefix: $environment-air-personalization-api-perf-jmeter
